export type {
    AverageSalary,
    AverageSalaryPoint,
    Category,
    CategoryKey,
    CountryKey,
    CurrencyCode,
    ExchangeRates,
    Holiday,
    Partner,
    Vacancy,
    VacancyLogoTone,
} from './domain'
export type {
    ApiFailure,
    ApiResponse,
    ApiSuccess,
    AverageSalaryResponse,
    CategoriesResponse,
    CountriesResponse,
    ExchangeRatesResponse,
    HolidaysResponse,
    PartnerResponse,
    PartnersResponse,
    VacanciesResponse,
    VacancyResponse,
} from './api'
